<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>BMPharma.CHIFA</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BMPharma.Domain\BMPharma.Domain.csproj" />
    <ProjectReference Include="..\BMPharma.Application\BMPharma.Application.csproj" />
    <ProjectReference Include="..\BMPharma.Persistence.PostgreSQL\BMPharma.Persistence.PostgreSQL.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>
</Project>
